# Form implementation generated from reading ui file 'Robot.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(660, 310, 49, 16))
        self.label.setObjectName("label")
        self.review = QtWidgets.QPushButton(parent=self.centralwidget)
        self.review.setGeometry(QtCore.QRect(1032, -1, 256, 100))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        self.review.setFont(font)
        self.review.setObjectName("review")
        self.bottomline = QtWidgets.QFrame(parent=self.centralwidget)
        self.bottomline.setGeometry(QtCore.QRect(0, 100, 1280, 1040))
        self.bottomline.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.bottomline.setLineWidth(3)
        self.bottomline.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.bottomline.setObjectName("bottomline")
        self.robot = QtWidgets.QPushButton(parent=self.centralwidget)
        self.robot.setGeometry(QtCore.QRect(258, -1, 260, 100))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        self.robot.setFont(font)
        self.robot.setObjectName("robot")
        self.navigate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.navigate.setGeometry(QtCore.QRect(774, -1, 260, 100))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        self.navigate.setFont(font)
        self.navigate.setObjectName("navigate")
        self.topline = QtWidgets.QFrame(parent=self.centralwidget)
        self.topline.setGeometry(QtCore.QRect(0, 69, 1280, 60))
        self.topline.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.topline.setLineWidth(3)
        self.topline.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.topline.setObjectName("topline")
        self.IGMRlogo = QtWidgets.QLabel(parent=self.centralwidget)
        self.IGMRlogo.setGeometry(QtCore.QRect(1191, 622, 89, 89))
        self.IGMRlogo.setText("")
        self.IGMRlogo.setPixmap(QtGui.QPixmap("Resource Files/igmr-v1-path.svg"))
        self.IGMRlogo.setScaledContents(True)
        self.IGMRlogo.setObjectName("IGMRlogo")
        self.localize = QtWidgets.QPushButton(parent=self.centralwidget)
        self.localize.setGeometry(QtCore.QRect(516, -1, 260, 100))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        self.localize.setFont(font)
        self.localize.setObjectName("localize")
        self.setup = QtWidgets.QPushButton(parent=self.centralwidget)
        self.setup.setGeometry(QtCore.QRect(0, -1, 260, 100))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        self.setup.setFont(font)
        self.setup.setObjectName("setup")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Robot"))
        self.review.setText(_translate("MainWindow", "Review"))
        self.robot.setText(_translate("MainWindow", "Robot"))
        self.navigate.setText(_translate("MainWindow", "Navigate"))
        self.localize.setText(_translate("MainWindow", "Localize"))
        self.setup.setText(_translate("MainWindow", "Setup"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
